---
- name: Instalar rclone
  apt: {name: rclone, state: present}

- name: Criar diret√≥rio GoogleDrive
  file:
    path: "{{ dev_home }}/GoogleDrive"
    state: directory
    owner: "{{ dev_user }}"
    group: "{{ dev_user }}"

- name: Subpastas
  file:
    path: "{{ dev_home }}/GoogleDrive/{{ item }}"
    state: directory
  loop: [Downloads, docs]
