---
- name: Instalar Celluloid
  apt: {name: celluloid, state: present}

- name: Instalar gThumb
  apt: {name: gthumb, state: present}

- name: Instalar Chrome
  apt: {deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb}

- name: Instalar Sublime Text
  apt_repository: {repo: "deb https://download.sublimetext.com/ apt/stable/"}

- name: Sublime
  apt: {name: sublime-text}

- name: Discord
  apt: {deb: "https://discord.com/api/download?platform=linux&format=deb"}
